/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;
import org.junit.Before;
import org.junit.Test;

import java.util.List;

import static org.junit.Assert.assertTrue;


public class LibraryTest {

    private SessionFactory sessionFactory;

    @Before
    public void setUp() throws Exception {
        sessionFactory = new Configuration().configure().buildSessionFactory();
    }

    @Test
    public void testSomeLibraryMethod() {
        try (Session session = sessionFactory.openSession()) {
            List<Series> series = session.createQuery("from Series s", Series.class).list();
            assertTrue(session.isOpen());
        }
    }
}
